name: pub-web-ofc-locations-ci-cd-pipeline

on: 
  push:
    branches: develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
          
      - name: Build with Maven
        run: mvn clean package
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          
      - name: Login to Amazon ECR
        id: aws-ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build Docker image
        env:
          AWS_ECR_REGISTRY: ${{ steps.aws-ecr-login.outputs.registry }}
          AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          DOCKER_IMAGE_TAG: latest
        run: |
          docker build -t $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$DOCKER_IMAGE_TAG .
          docker push $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$DOCKER_IMAGE_TAG
